spring:
  profiles:
    active:  local

  jpa:
    hibernate.naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl

---

spring:
  profiles: local

  jpa:
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:mysql://localhost:23306/apmdb?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: anypoint
    password: media

  redis:
    host: localhost
    port: 26379
